
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2M7-SVLsUa2rW9mpvSr7f2o6vEI0HDs0',
    appId: '1:934169103159:web:a4467537d57747da0b28b2',
    messagingSenderId: '934169103159',
    projectId: 'reading-habit-app',
    authDomain: 'reading-habit-app.firebaseapp.com',
    storageBucket: 'reading-habit-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOlXW8VhjaZ5YhzgwNdE5f3DLKF0DyUXE',
    appId: '1:934169103159:android:61bf2358bf95185c0b28b2',
    messagingSenderId: '934169103159',
    projectId: 'reading-habit-app',
    storageBucket: 'reading-habit-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwIXDRc_uhWvycn4Wy7G1oNqQ3HmIn4Xo',
    appId: '1:934169103159:ios:2972e35880687e850b28b2',
    messagingSenderId: '934169103159',
    projectId: 'reading-habit-app',
    storageBucket: 'reading-habit-app.firebasestorage.app',
    iosClientId: '934169103159-5as5j6riq7k4u60ul5o2i712mb0fg720.apps.googleusercontent.com',
    iosBundleId: 'com.example.readingHabitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2M7-SVLsUa2rW9mpvSr7f2o6vEI0HDs0',
    appId: '1:934169103159:web:1f19bf6c7e07f9080b28b2',
    messagingSenderId: '934169103159',
    projectId: 'reading-habit-app',
    authDomain: 'reading-habit-app.firebaseapp.com',
    storageBucket: 'reading-habit-app.firebasestorage.app',
  );

}